id: PFF8C7BE6
initial_creation_type: input
source_metadata:
  Title: Jñānaśrimitra’s Anupalabdhirahasya and Sarvaśabdābhāvacarcā
  Editor: '-'
  Publisher: Arbeitskreis Fur Tibetische Und Buddhistische Studien, Universitat Wien
  Place of Publication: Wien
  Year: '2007'
  Sarvaśabdabhāvacarcā:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: May 2017
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:03:04.762636'
last_modified_at: '2022-03-08T17:03:04.762645'
